### ISSUE TITLE
Bugfix: broken functionality and tests

### ISSUE THREAD

**Issue by StoicDeveloper** [123kevyd/recipeasy#144]
BUG:
action - in kitchen, enter new ingredient in autocomplete entry bar, press enter
result - 
TypeError: Cannot read property 'dataValues' of undefined
    at handler (webpack-internal:///(api)/./pages/api/ingredients.js:13:20)
Probably Cause - ingredient controller is not parsing the stringified request body
Vinh said that the fetch API, if given a correct content header in the request, will automatically stringify the body, and it will be (automatically) parsed in the backend. I didn't know this, so the code in store/user_store.js stringifies all request bodies, though the backend code expects pre-parsed objects. I wasn't able to get the automatic parsing to work, instead the object would not survive network transit, and would arrive as a '[object Object]' string, resulting in a "unexpected token o while parsing JSON" error.

BUG: 
action - in kitchen, enter a new restriction in autocomplete entry bar, press enter
result - 
failed to find dependency in models/index.js
Error: Cannot find module '/home/user/Projects/recipeasy/.next/server/pages/api/ingredients.js'
    at webpackEmptyContext (/home/user/Projects/recipeasy/.next/server/pages/api/restrictions.js:22:10)
    at eval (webpack-internal:///(api)/./backend/models/index.js:31:73)
    at Array.forEach (<anonymous>)
    at eval (webpack-internal:///(api)/./backend/models/index.js:29:4)
    at Object.(api)/./backend/models/index.js (/home/user/Projects/recipeasy/.next/server/pages/api/restrictions.js:94:1)
    at __webpack_require__ (/home/user/Projects/recipeasy/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./backend/controllers/restriction_controller.js:1:12)
    at Object.(api)/./backend/controllers/restriction_controller.js (/home/user/Projects/recipeasy/.next/server/pages/api/restrictions.js:72:1)
    at __webpack_require__ (/home/user/Projects/recipeasy/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./pages/api/restrictions.js:5:21) {
  code: 'MODULE_NOT_FOUND'
}
Also a restriction with no title will appear in the restriction bar.
NOTE: the code that creates this stack trace was added by me in line 33 of models/index.js, to prevent it from searching for dependencies that it shouldn't. The stack trace might not actually be related to the failure to create the restriction. Focus on that.

At the moment tests all work on dev, make sure they still work after fixing these errors.

**Comment by StoicDeveloper** [comment]
Note that creating a new equipment also creates the same stack trace, but succeeds in creating the new item. Only ingredients and restrictions don't work
